### ISSUE TITLE
Decompressing Common Crawl archive fails

### ISSUE THREAD

**Issue by bgamari** [snoyberg/zlib-bindings#10]
Strangely `zlib-bindings-0.1.1.5` returns a truncated result while decompressing one of the Common Crawl WARC archives.

Consider `ZTest.hs`,
```haskell
import Control.Monad (unless)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Lazy as LBS
import qualified Codec.Compression.Zlib    as ZC
import qualified Codec.Zlib                as Z

main :: IO ()
main = do
    bs <- LBS.getContents
    let wbits = ZC.WindowBits 31
    inf <- Z.initInflate wbits

    let doChunk = \bs -> do
            --putStrLn $ "chunk of length "++show (BS.length bs)
            popper <- Z.feedInflate inf bs
            fromPopper popper
    r <- LBS.foldrChunks (\chunk rest -> doChunk chunk >> rest) (return ()) bs
    bs <- Z.finishInflate inf
    unless (BS.null bs) (BS.putStr bs)
    return r

fromPopper :: Z.Popper -> IO ()
fromPopper pop = loop where
    loop = do
      mbs <- pop
      case mbs of
         Nothing -> return ()
         Just bs -> {- putStr "POP" >> -} BS.putStr bs >> loop
```

Which produces,
```
$ s3cmd get s3://aws-publicdatasets/common-crawl/crawl-data/CC-MAIN-2015-40/segments/1443736672328.14/warc/CC-MAIN-20151001215752-00004-ip-10-137-6-227.ec2.internal.warc.gz .
$ ls -lh CC-MAIN-20151001215752-00004-ip-10-137-6-227.ec2.internal.warc.gz 
-rw-r--r-- 1 ben ben 911M Nov  8 19:04 laura/CC-MAIN-20151001215752-00004-ip-10-137-6-227.ec2.internal.warc.gz
$ ghc ZTest.hs
$ ./ZTest < CC-MAIN-20151001215752-00004-ip-10-137-6-227.ec2.internal.warc.gz
WARC/1.0
WARC-Type: warcinfo
WARC-Date: 2015-11-08T18:57:42Z
WARC-Record-ID: <urn:uuid:c209e6ae-6c12-479e-a202-ca0226119f07>
Content-Length: 345
Content-Type: application/warc-fields
WARC-Filename: CC-MAIN-20151001215752-00004-ip-10-137-6-227.ec2.internal.warc.gz

robots: classic
hostname: ip-10-137-6-227.ec2.internal
software: Nutch 1.6 (CC)/CC WarcExport 1.0
isPartOf: CC-MAIN-2015-40
operator: CommonCrawl Admin
description: Wide crawl of the web for September 2015
publisher: CommonCrawl
format: WARC File Format 1.0
conformsTo: http://bibnum.bnf.fr/WARC/WARC_ISO_28500_version1_latestdraft.pdf


$
```

This is significantly shorter than the 4GByte result I was expecting.

Judging from the commented-out debug output, I believe only the final `finishInflate` is producing any output at all.

**Comment by bgamari** [comment]
It appears that `inflate` may be returning `Z_STREAM_END` even after seeing only the first chunk.

These public data-sets unfortunately have a reputation for being a bit odd; it wouldn't surprise me if this file is in fact just a concatenation of number `gzip` streams. It's a bit odd that `gzip` doesn't mind this.

**Comment by snoyberg** [comment]
The zlib-bindings package is deprecated in favor of streaming-commons, can
you try using that package instead and see if the problem persists?

**Comment by bgamari** [comment]
> The zlib-bindings package is deprecated in favor of streaming-commons, can you try using that package instead and see if the problem persists?

I'm afraid that `streaming-common` won't quite do the trick; while it provides a means of recovering after we hit the end of the stream, it has no way to detect this condition if you do not know the expected length of the output.

**Comment by snoyberg** [comment]
Closing in favor of the streaming-commons issue. I believe the diagnosis here is not correct.
